matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.4

language: node_js
node_js:
  - "8.12.0"
sudo: required

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE

install:
- npm install
- npm install -g codecov

script:
  - npm test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist:mwl:publish; fi

after_success:
- bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
