matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.4

language: node_js
node_js:
  - "8.12.0"
sudo: required

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

script:
  - npm test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist:mwl:publish; fi