matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.4

language: node_js
node_js:
  - "12.10.0"
sudo: required

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE

install:
- npm install
- npm install -g codecov
- npm rebuild

script:
  - npm test
  - npm run postinstall
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist:linux:publish; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist:mac:publish; fi

after_success:
- bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
